### ISSUE TITLE
astro-htmx does not support astro 4.0

### ISSUE THREAD

**Issue by chandy** [xstevenyung/astro-htmx#2]
When trying to install astro-htmx onto a Astro 4.0+ project it fails because this package does not support it.

> ~/D/w/h/astro/beneficial-bar is 📦 v0.0.1 via  v18.18.0 took 1d5h15m27s 
❯ npm i astro-htmx
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: beneficial-bar@0.0.1
npm ERR! Found: astro@4.0.6
npm ERR! node_modules/astro
npm ERR!   astro@"^4.0.6" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer astro@"^3.0.0" from astro-htmx@1.0.3
npm ERR! node_modules/astro-htmx
npm ERR!   astro-htmx@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR!

**Comment by excessivecoding** [comment]
thanks for reporting.

fixed in astro-htmx 1.0.5
