### ISSUE TITLE
astro build vite shouts a warning about htmx

### ISSUE THREAD

**Issue by jrvidotti** [xstevenyung/astro-htmx#3]
I am getting a warning from vite builder about htmx:

```
 building client (vite) 
node_modules/.pnpm/htmx.org@1.9.10/node_modules/htmx.org/dist/htmx.min.js (1:5388) 
Use of eval in "node_modules/.pnpm/htmx.org@1.9.10/node_modules/htmx.org/dist/htmx.min.js" 
is strongly discouraged as it poses security risks and may cause issues with minification.
```

Uninstalling astro-htmx and putting manually the htmx head tags manually does not throw this warning.

**Comment by excessivecoding** [comment]
from my understanding, there is not much that can be done to fix this warning as it's coming from htmx itself.
if you install htmx directly from npm, my guess is that you would have the same issue.

P.S. the warning is not appearing when using the CDN version because vite doesn't have to process it

**Comment by excessivecoding** [comment]
found this issue on the htmx repo https://github.com/bigskysoftware/htmx/issues/1944

closing as there is nothing that can be done on this specific package
