### ISSUE TITLE
Why `htmx` variable is not available in the browser?

### ISSUE THREAD

**Issue by gkossakowski** [xstevenyung/astro-htmx#5]
Hi,

I'm using your integration and I wanted to debug some htmx-related issue. The debugging instructions mention method on `htmx` variable: https://htmx.org/docs/#debugging

I can't seem to be able to access it from browser's console when using astro-htmx. However, if I install htmx manually, it works. Is this limitation intentional on astr-htmx's side?

**Comment by excessivecoding** [comment]
Hello,

It was a limitation of `astro-htmx`. I just published `astro-htmx` 1.0.6 which should expose `htmx` in the browser now.

closing but feel free to reopen if you stumble upon issue with the update
